version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: penalties_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: penalties_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - penalties_pgdata:/var/lib/postgresql/data

volumes:
  penalties_pgdata: