server:
  port: 8085

spring:
  application:
    name: penalty-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/penalties_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_RESOURCE_SERVER_URL:http://localhost:8080/realms/vmeste.tech}

integration:
  services:
    user-service:
      url: ${INTEGRATION_USER_SERVICE_URL:http://localhost:8082}
      name: ${INTEGRATION_USER_SERVICE_NAME:user-service}
    task-service:
      url: ${INTEGRATION_TASK_SERVICE_URL:http://localhost:8083}
      name: ${INTEGRATION_TASK_SERVICE_NAME:task-service}
    rules-service:
      url: ${INTEGRATION_RULES_SERVICE_URL:http://localhost:8084}
      name: ${INTEGRATION_RULES_SERVICE_NAME:rules-service}
