server:
  port: 8085

spring:
  application:
    name: penalty-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/penalty_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_ISSUER_URI:http://localhost:8080/realms/test-realm}

integration:
  services:
    user-service:
      url: ${INTEGRATION_USER_SERVICE_URL:http://localhost:8082}
      name: ${INTEGRATION_USER_SERVICE_NAME:user-service}
